# Generated by Django 4.1 on 2024-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="color",
            field=models.CharField(default="#000000", max_length=7),
        ),
    ]
