# Generated by Django 4.1 on 2024-11-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_created_at_remove_post_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="blog/images/%Y/%m/%d"),
        ),
    ]
