# Generated by Django 4.1 on 2024-12-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file_upload",
            field=models.FileField(blank=True, upload_to="community/files/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, upload_to="community/images/%Y/%m/%d"),
        ),
    ]
