# Generated by Django 4.1 on 2024-12-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="slug",
        ),
    ]
