# Generated by Django 4.1 on 2024-12-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_author_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
    ]
