# Generated by Django 4.1 on 2024-12-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_page", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
